INSERT INTO Nutritionix_Nutrient_Field_Map (attr_id,usda_tag,name,unit,bulk_csv_field)
VALUES       (203,"PROCNT","Protein","g","nf_protein"),
             (204,"FAT","Total lipid (fat)","g","nf_total_fat"),
             (205,"CHOCDF","Carbohydrate, by difference","g","nf_total_carbohydrate"),
             (208,"ENERC_KCAL","Energy","kcal","nf_calories"),
             (269,"SUGAR","Sugars, total","g","nf_sugars"),
             (291,"FIBTG","Fiber, total dietary","g","nf_dietary_fiber"),
             (301,"CA","Calcium, Ca","mg","nf_calcium_mg"),
             (303,"FE","Iron, Fe","mg","nf_iron_mg"),
             (306,"K","Potassium, K","mg","nf_potassium"),
             (307,"NA","Sodium, Na","mg","nf_sodium"),
             (324,"VITD","Vitamin D","IU","nf_vitamin_d_mcg"),
             (539,"SUGAR_ADD","Sugars, added","g","nf_added_sugars"),
             (601,"CHOLE","Cholesterol","mg","nf_cholesterol"),
             (605,"FATRN","Fatty acids, total trans","g","nf_trans_fatty_acid"),
             (606,"FASAT","Fatty acids, total saturated","g","nf_saturated_fat");
